// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2MKg6jZBUzSUZR2_Jfw05dSVPIr--3s',
    appId: '1:265120766102:web:f18c01a8a2f6873a6b0ab7',
    messagingSenderId: '265120766102',
    projectId: 'click-game-8af15',
    authDomain: 'click-game-8af15.firebaseapp.com',
    storageBucket: 'click-game-8af15.appspot.com',
    measurementId: 'G-J2HNCVGKFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYv0ldFEjp56kxraHRjeDtxV8GEsieQbw',
    appId: '1:265120766102:android:1f9742303c64b6e06b0ab7',
    messagingSenderId: '265120766102',
    projectId: 'click-game-8af15',
    storageBucket: 'click-game-8af15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjjRyrrU9nErvY0mM91nuHGa0-8vQmtHM',
    appId: '1:265120766102:ios:dfce5f0f6d06a0096b0ab7',
    messagingSenderId: '265120766102',
    projectId: 'click-game-8af15',
    storageBucket: 'click-game-8af15.appspot.com',
    iosClientId: '265120766102-vpcbdslgpgiei0s9drb4ogn02k074tr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjjRyrrU9nErvY0mM91nuHGa0-8vQmtHM',
    appId: '1:265120766102:ios:dfce5f0f6d06a0096b0ab7',
    messagingSenderId: '265120766102',
    projectId: 'click-game-8af15',
    storageBucket: 'click-game-8af15.appspot.com',
    iosClientId: '265120766102-vpcbdslgpgiei0s9drb4ogn02k074tr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickgame',
  );
}
